<Project Sdk="MSTest.Sdk/3.8.2">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Mas.Infrastructure.ServiceRegistry/Mas.Infrastructure.ServiceRegistry.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="Microsoft.Testing.Extensions.TrxReport" Version="1.8.4" />
      <PackageReference Update="Microsoft.NET.Test.Sdk" Version="17.14.1" />
      <PackageReference Update="Microsoft.Testing.Extensions.CodeCoverage" Version="17.14.2" />
      <PackageReference Update="MSTest.TestFramework" Version="3.10.4" />
      <PackageReference Update="MSTest.TestAdapter" Version="3.10.4" />
    </ItemGroup>

</Project>
