<Project Sdk="MSTest.Sdk/3.8.2">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="../Mas.Infrastructure.ServiceRegistry/Mas.Infrastructure.ServiceRegistry.csproj"/>
    </ItemGroup>

</Project>
